### ISSUE TITLE
[Bug] Only package with lower case loader name

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_github_source#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

This is the only Fivetran package I use that has `fivetran` as the loader, instead of `Fivetran`.

### Relevant error log or model output

```shell
N/A
```

### Expected behavior

Loader should be called `Fivetran`

### dbt Project configurations

N/A

### Package versions

0.7.0

### What database are you using dbt with?

snowflake

### dbt Version

1.5

### Additional Context

<img width="135" alt="image" src="https://github.com/fivetran/dbt_github_source/assets/6558178/51ab8e80-98ba-4710-b75f-76778283d6ca">

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by raphaelvarieras** [comment]
Sure, the ones I see that have the upper case "F" at the moment are:
- apple_store
- facebook_pages
- google_play
- instagram_business
- linkedin_pages
- twitter_organic

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing @raphaelvarieras I did a review myself of a number of packages and found that this "F" and "f" seems to be inconsistent across the packages and there is no real standard pattern. I feel this is a good point to use "F" as the standard going forward. 

I'll review your PR and let you know if I have any questions!

**Comment by fivetran-joemarkiewicz** [comment]
@raphaelvarieras your PR has since been merged into the `main` branch and has been released within v0.7.1. It should be live at the top of the hour. Thanks again for your contribution!
