### ISSUE TITLE
Error "invalid identifier 'BIO'" in model stg_github__user

### ISSUE THREAD

**Issue by andehen** [fivetran/dbt_github_source#9]
I run into this error when trying to run this package against our github source schema replicated by Fivetran.
```
$ dbt run -m stg_github__user

...

ERROR creating table model dbt_andehen.stg_github__user.......

Database Error in model stg_github__user (models/stg_github__user.sql)
  000904 (42000): SQL compilation error: error line 11 at position 8
  invalid identifier 'BIO'
  compiled SQL at target/run/github_source/models/stg_github__user.sql
```

Info:
* db: Snowflake
* dbt v0.19.0
* fivetran/github_sources v0.2.1

**Comment by fivetran-joemarkiewicz** [comment]
Hi @andehen my initial thought with the error you are seeing is due to a previous release of this package causing conflicts. Would you be able to clear and reinstall your projects package dependencies:
```
dbt clean && dbt deps
```
It also may be helpful to try and run `dbt run --full-refresh` after reinstalling the packages. Our prior Github package release included the bio field in the user table, while it is no longer included in the current release. This may be what is causing the model to fail on your end. 

Let me know if these proposed changes fix the error.

Thanks!

**Comment by andehen** [comment]
Thanks for your reply!

I run the following
```
[nix-shell:~/kolonial/dev/dbt-models/snowflake]$ dbt clean && dbt deps
Running with dbt=0.19.0
Checking target/*
 Cleaned target/*
Checking dbt_modules/*
 Cleaned dbt_modules/*
Finished cleaning all paths.
Running with dbt=0.19.0
Installing fishtown-analytics/dbt_utils@0.6.4
  Installed from version 0.6.4

Installing fivetran/github@0.2.0
  Installed from version 0.2.0

Installing fivetran/github_source@0.2.1
  Installed from version 0.2.1

Installing https://github.com/fivetran/dbt_fivetran_utils.git@master
  Installed from revision master
```

and then

```
$ dbt run -m +stg_github__user --full-refresh

Running with dbt=0.19.0

09:37:20 | Concurrency: 8 threads (target='dev')
09:37:20 |
09:37:20 | 1 of 2 START view model dbt_andehen.stg_github__user_tmp............. [RUN]
09:37:21 | 1 of 2 OK created view model dbt_andehen.stg_github__user_tmp........ [SUCCESS 1 in 1.78s]
09:37:21 | 2 of 2 START table model dbt_andehen.stg_github__user................ [RUN]
09:37:26 | 2 of 2 ERROR creating table model dbt_andehen.stg_github__user....... [ERROR in 4.13s]
09:37:27 |
09:37:27 | Finished running 1 view model, 1 table model, 1 hook in 13.23s.

Completed with 1 error and 0 warnings:

Database Error in model stg_github__user (models/stg_github__user.sql)
  000904 (42000): SQL compilation error: error line 11 at position 8
  invalid identifier 'BIO'
  compiled SQL at target/run/github_source/models/stg_github__user.sql

Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

So still have this issue.

**Comment by fivetran-joemarkiewicz** [comment]
Hmm strange that didn't work. I just upgraded to dbt 0.19.0 on my end and ran the same in my Snowflake environment but was not able to replicate the same error. Would you be able to share the compiled SQL for this run (you should be able to click the link in the terminal at `compiled SQL at target/run/github_source/models/stg_github__user.sql`)?

We may be able to see where the 'BIO' field is coming in by taking a look at the compiled sql from the run and adjust accordingly.

**Comment by fivetran-kristin** [comment]
One thought is that this might be due to a quoting issue in snowflake, but we won't know until we can replicate what is going on.
@andehen, in addition to what @fivetran-joemarkiewicz requested, can you also share:
- A screenshot of your `dbt_project.yml` file, specifically if/where any quoting configuration is set up
- A screenshot of the Fivetran-created, `user` table columns in Snowflake.  For example, I'm looking for something like this:
![Screen Shot 2021-02-11 at 8 37 43 AM](https://user-images.githubusercontent.com/54283769/107667513-7ca9a280-6c44-11eb-87b4-5c776679d3ae.png)

**Comment by andehen** [comment]
Did some more debugging myself and the issue is that `bio` is still in the models configuration file here https://github.com/fivetran/dbt_github_source/blob/c3f4ce66a5e42fbe9cea0e93e3aec07d1316cb64/models/stg_github.yml#L198

Causes this query to be executed as part of running the model
```
alter table analytics.dbt_andehen.stg_github__user alter
    
        user_id COMMENT $$System generated unique id for the user.$$ ,
    
        login_name COMMENT $$The alias the user uses to login to github.$$ ,
    
        name COMMENT $$The name of the user$$ ,
    
        company COMMENT $$The  company of the user.$$ ,
    
        bio COMMENT $$The new short biography of the user$$ ;
```
which fails as `bio` is no longer included in the model. Didn't spot it at first, just had a look a the compiled model which looked fine. So couldn't understand where this `bio` identifier was coming from.

**Comment by fivetran-kristin** [comment]
@andehen - great catch!!

I've pushed a fix for this. Can you please test that it works for you by removing your current github dependency, and adding the github_source package dependency using the following syntax in your `packages.yml` file?

```
packages:
  - git: https://github.com/fivetran/dbt_github_source.git
    revision: bug_fix/bio
    warn-unpinned: false
```

After you update your `packages.yml` file, you will need to run:
`dbt clean`
`dbt deps`
`dbt run --full-refresh`

Keep us posted! If this works, will merge the change into master & publish a new package release with this fix.

**Comment by andehen** [comment]
Worked! :tada:

**Comment by fivetran-kristin** [comment]
@andehen We just released new versions of the github package! You can update your packages.yml file to the following for this bug fix:

```
packages:
  - package: fivetran/github
    version: 0.2.1
```

**Comment by andehen** [comment]
Great! Thanks @fivetran-kristin !
